- name: Mettre à jour les packages Debian
  hosts: debian
  become: no
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Mettre à jour les paquets installés
      apt:
        upgrade: 'dist'
        purge: yes
        autoremove: yes
        autoclean: yes