---
- name: Update Red Hat packages
  hosts: redhat
  become: yes
  tasks:
    - name: Gather facts
      setup:

    - name: get upgradable packages
      yum:
        list: updates
      register: upgradable_packages
    - name: Update package list
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Update installed packages
      yum:
        name: "{{ upgradable_packages.results }}"
        state: latest