- name: Update Red Hat packages
  hosts: redhat
  become: yes
  tasks:
    - name: Update package list
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Update installed packages
      yum:
        name: "{{ ansible_facts.packages | difference(ansible_facts.packages_upgradable) }}"
        state: latest