---
- name: Mettre à jour les packages Red Hat
  hosts: redhat
  become: no
  tasks:
    - name: Mettre à jour la liste des paquets
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Mettre à jour les paquets installés
      yum:
        name: '{{ ansible_facts.packages | difference(ansible_facts.packages_upgradable) }}'
        state: latest


        reh-upgrade.yml
